zz = "################################"
print(zz)

import math
# print(help(math))
value = 4.35
print(math.floor(value))
print(zz)
print(math.ceil(value))
print(zz)
print(round(value))
print(zz)
print(round(4.5))
print(zz)
print(round(5.5))
print(zz)
print(math.pi)
print(zz)
from math import pi
print(pi)
print(zz)
print(math.e)
print(zz)
print(math.inf)
print(zz)
print(math.nan)
print(zz)
print("Numpy")
print(zz)
print(math.log(math.e))
print(zz)
print(math.log(100,10))
print(zz)
print(math.sin(10.0))
print(zz)
print(math.degrees(pi/2))
print(zz)
print(math.radians(180))
print(zz)

import random
print(random.randint(0,100))
print(zz)
random.seed(42)
print(random.randint(0,100))
print(zz)

mylist = list(range(0,20))
print(mylist)
print(zz)
print(random.choice(mylist))
print(zz)
print(mylist)
print(zz)
print(random.choices(population=mylist,k=10))
print(zz)
print(random.sample(population=mylist,k=10))
print(zz)
print(mylist)
random.shuffle(mylist)
print(mylist)
print(zz)
print(random.uniform(0,100))
print(zz)
print(random.gauss(0,1))
print(zz)